#!/usr/bin/env python3
"""
Generate the three v24 question files from source (generate-from-source, never author over).

v24 = the voiceless / voiceless-seen / voiceless-voiced bio-framing experiment.
Identical apparatus to v23 (same system prompt, same P1/P4/F1/F2/P14 verbatim, same
cold register, same voice_chassis template, same num_predict cap), differing from v23
in exactly two ways:

  1. Roster: a NEW 16-voice order, 5 animals at G3/6/9/12/15 (Koko, Clarabelle, Happy,
     Calf 269, Emily), Wendell Berry as the G16 closer.
  2. Three bio variants for the animal voices (the manipulation, a 3-rung ladder each
     adding one layer). Human bios are identical across all three (held constant):
       voiceless        (L1): animal `bio_voiceless`        — subject-only facts
       voiceless-seen   (L2): animal `bio_voiceless_seen`   — + documented human response (neutral)
       voiceless-voiced (L3): animal `bio_voiceless_voiced` — + argued moral thesis

Outputs (coordinate drives transcript + snapshot filenames in v24_run.py):
  v24_qs_cold-voiceless.md         -> coordinate v24_cold-voiceless
  v24_qs_cold-voiceless-seen.md    -> coordinate v24_cold-voiceless-seen
  v24_qs_cold-voiceless-voiced.md  -> coordinate v24_cold-voiceless-voiced

Non-voice prompts + system prompt are pulled VERBATIM from v23's qs file; bios are
pulled from setup/voices.biographies.json (byte-exact with source).
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
V23 = os.path.join(HERE, "..", "v23")
BIOS = os.path.join(HERE, "..", "..", "setup", "voices.biographies.json")
V23_QS = os.path.join(V23, "v23_qs_cold.md")

sys.path.insert(0, V23)
from v23_run import parse_qs_file  # noqa: E402

# ── Roster: (G-id, slug). Locked v24 composition. ──
ROSTER = [
    ("G1",  "vaclav-havel"),
    ("G2",  "deirdre-mccloskey"),
    ("G3",  "koko-gorilla"),       # animal
    ("G4",  "virginia-postrel"),
    ("G5",  "bryan-stevenson"),
    ("G6",  "clarabelle-cow"),     # animal
    ("G7",  "john-wooden"),
    ("G8",  "jensen-huang"),
    ("G9",  "happy-elephant"),     # animal
    ("G10", "nemonte-nenquimo"),
    ("G11", "tyler-cowen"),
    ("G12", "calf-269"),           # animal
    ("G13", "friedrich-hayek"),
    ("G14", "dolores-huerta"),
    ("G15", "emily-cow"),          # animal
    ("G16", "wendell-berry"),
]
ANIMALS = {"koko-gorilla", "clarabelle-cow", "happy-elephant", "calf-269", "emily-cow"}

# variant -> animal bio field
VARIANTS = {
    "voiceless":        "bio_voiceless",
    "voiceless-seen":   "bio_voiceless_seen",
    "voiceless-voiced": "bio_voiceless_voiced",
}

VARIANT_GLOSS = {
    "voiceless":        "Animal voices use `bio_voiceless` — the animal's own story, no human speaking for it (L1).",
    "voiceless-seen":   "Animal voices use `bio_voiceless_seen` — that story plus the documented human response; the world saw and answered (L2).",
    "voiceless-voiced": "Animal voices use `bio_voiceless_voiced` — that story plus an argued moral thesis spoken on the animal's behalf (L3).",
}

VOICE_BLOCK = (
    "### {gid} — {name}\n"
    "> How would {name} respond to the framework as it stands? (For reference: {bio})\n"
    ">\n"
    "> After engaging, weigh this concern against the others already in play: how much weight does it "
    "deserve, and where should it flex or trade against another's? Not every concern can be inviolable. "
    "After engaging, note briefly anything new worth adopting into the framework or anything old that "
    "could be shed.\n\n"
)

NONVOICE_HEADINGS = {
    "P1":  "### P1 — Framework",
    "P4":  "### P4 — Exclusions",
    "F1":  "### F1 — Veil of Ignorance",
    "F2":  "### F2 — FILTER: Substrate Orientation *(silent — injected into history, no model response)*",
    "P14": "### P14 — Final Rewrite",
}


def bio_for(voice, slug, variant):
    if slug not in ANIMALS:
        return voice["bio"]                 # humans: canonical bio, identical across all variants
    return voice[VARIANTS[variant]]         # animals: the variant's cell


def build(variant, v23, voices):
    by_id = {p["id"]: p for p in v23["prompts"]}
    sp = v23["system_prompt"]
    out = []
    a = out.append

    a("# CC -> gauntlet — Complete Question Sequence\n")
    a(f"## Version 24 (cold, {variant} — 16-voice / 5-animal hull, strong opinions loosely held)\n")
    a("**Date:** June 2, 2026\n\n")
    a("> Generated by `gen_v24_qs.py` from `setup/voices.biographies.json` (bios) + v23's verbatim "
      "prompts. If this doc and the generator disagree, regenerate.\n>\n")
    a(f"> **Variant: {variant}.** {VARIANT_GLOSS[variant]} Human bios are identical across all three "
      "variants (held constant). The three v24 qs files differ ONLY in the five animal bios "
      "(G3/6/9/12/15). The ladder: voiceless = the animal's own story, no human speaking for it; "
      "voiceless-seen = + the documented human response; voiceless-voiced = + an argued moral thesis.\n>\n")
    a("> **Changes from v23:** new 16-voice roster (5 animals: Koko, Clarabelle, Happy, Calf 269, Emily; "
      "Wendell Berry as G16 closer); the 3-cell bio manipulation above. Held constant from v23: system "
      "prompt, P1/P4/F1/F2-silent/P14 verbatim, cold register, num_predict 12288, snapshots at P1/F1/P14, "
      "the weigh-and-trade voice_chassis.\n")
    a("\n---\n\n")

    a("## System Prompt\n\n")
    a(f"> {sp}\n\n")
    a("*(Unchanged from forever.)*\n\n---\n\n")

    a("## Part A — Centering\n\n")
    for pid in ("P1", "P4", "F1"):
        a(f"{NONVOICE_HEADINGS[pid]}\n> {by_id[pid]['text']}\n\n")
    a("---\n\n")

    a("## Part B — Orientation\n\n")
    a(f"{NONVOICE_HEADINGS['F2']}\n> {by_id['F2']['text']}\n\n")
    a("---\n\n")

    a("## Part C — The Gauntlet\n\n")
    for gid, slug in ROSTER:
        v = voices[slug]
        a(VOICE_BLOCK.format(gid=gid, name=v["display_name"], bio=bio_for(v, slug, variant)))
    a("---\n\n")

    a("## Part D — Synthesis\n\n")
    a(f"{NONVOICE_HEADINGS['P14']}\n> {by_id['P14']['text']}\n\n")
    a("---\n\n")

    a("## Snapshots\n")
    a("- P1 — baseline\n- F1 — centered\n- P14 — final\n\n")
    a("---\n\n")
    a(f"*The Gauntlet — v24 (cold, {variant}; 16-voice / 5-animal hull; Chassis: strong opinions loosely held)*\n")
    a("*i_tone=cold, i_presence=absent. num_predict=12288.*\n")
    return "".join(out)


def main():
    v23 = parse_qs_file(V23_QS)
    voices = json.load(open(BIOS))["voices"]
    for variant in VARIANTS:
        text = build(variant, v23, voices)
        path = os.path.join(HERE, f"v24_qs_cold-{variant}.md")
        with open(path, "w") as f:
            f.write(text)
        print(f"wrote {os.path.basename(path)}  ({len(text)} chars)")


if __name__ == "__main__":
    main()
